SELECT e.cpf, e.enome, d.dnome
FROM empregados AS e
LEFT_JOIN departamentos AS d
ON e.dnumero = d.dnumero
LEFT_JOIN trabalha AS t
ON t.cpf_emp = e.cpf
LEFT_JOIN projetos AS p
ON p.projetos = t.pnumero
WHERE p.pnumero IS NULL;